### ISSUE TITLE
Install PhantomJS

### ISSUE THREAD

**Issue by justahero** [Asquera/wheelmap-devenv#2]
Adjust install script to also install a working version of PhantomJS. This package is required for running Capybara tests.

**Comment by 1000miles** [comment]
The command `$ sudo apt-get install phantomjs` on Ubuntu 12.04 somehow did not work for me, I always got an error: 

```
Cliver::Dependency::VersionMismatch:
Could not find an executable 'phantomjs' that matched the requirements '>= 1.8.1', '< 3.0'. Found versions were {"/usr/bin/phantomjs"=>"2016"}.
```

Upgrading Poltergeist with `$ bundle update poltergeist` did not work either.

I tried to install it with: 

```
$ sudo npm install -g phantomjs-prebuilt
```

and that seems to get the tests running again.

Do you think the npm install could also be an alternative to mention?

**Comment by emig** [comment]
We have phantomjs working on this setup https://github.com/sozialhelden/wheelmap/pull/431, with some [tweaks](https://github.com/sozialhelden/wheelmap/pull/431/commits/4a673c892ffa7cea8c67cbf7031093ef8b781b7d) , but working
